### ISSUE TITLE
hazardlib error when hamlet sends TRT='*' to the ContextMaker

### ISSUE THREAD

**Issue by kejohnso** [GEMScienceTools/hamlet#16]
**I do not know if this is a hamlet issue or an engine issue.**

I tried to reproduce a hamlet error given by a user but instead got a different error: 
`File "/Users/kjohnson/GEM/oq-engine/openquake/hazardlib/contexts.py", line 342, in __init__
    [(_, self.mags)] = oq.mags_by_trt.items()`
`ValueError: too many values to unpack (expected 1)` 

At this line, I found that `trt='*' ` (i.e. running all trts instead of specifying one). I was able to make hamlet run by changing lines 337-338 to: 
`try:`
`    if trt == '*':`
`        self.mags = [item for sublist in oq.mags_by_trt.values() for item in sublist]`
`    else:`
`        self.mags = oq.mags_by_trt[trt]`
                    
In case it's relevant: this is the first time encountering this error and also the first time I've run hamlet since using python3.10 and upgrading to macOS 13.5.1

**Comment by micheles** [comment]
Should I do something on this or the issue is to be closed?

**Comment by kejohnso** [comment]
I would like to solve this - will review the problem next week

**Comment by kejohnso** [comment]
I'm no longer able to reproduce this error, so let's close the issue.
